### ISSUE TITLE
how do i download the whole season ?

### ISSUE THREAD

**Issue by xSyrix** [amraymanaly/kissdownloader#1]
@amraymanaly 

I am trying to download the whole season eg http://kissanime.to/Anime/Gundam-Reconguista-in-G

may i know how is the command supposed to be ?

i tried this ./kissdownloader -s "http://kissanime.to/Anime/Gundam-Reconguista-in-G" "002"

it only download 1 episode. 

how do i provide as many links as is technically possible to download the entire season 

please advise

**Comment by amraymanaly** [comment]
It assumes 002 is the episode number you want to download. To download all
episodes you have to give all episode numbers. So if the season or series
is 62 episodes for eg, you write './kissanime -s "
http://kissanime.to/Anime/Gundam-Reconguista-in-G" {1..60}' and bash will
expand {1..60} to be 1 2 3 4 ... 60. I hope that helps. The script is still
not complete so I don't expect it to be bug free, but I've been busy lately
so I'll finish it as soon as possible. I'll add a --all option as a
shorthand for the trick above too. Thanks for stopping by ;)

**Comment by xSyrix** [comment]
@amraymanaly 

thank you for the fast reply and time spend on writing this tool. keep up the good work 

cheers
